// import img1 from ".";
const products = [
  // spick
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/20.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/21.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/22.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/23.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/24.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/25.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/26.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/27.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/28.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/29.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "spick",
    image: "images/spick/30.JPG",
    price: 829.99,
  },

  // bubble
  {
    _id: "31",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/1.JPG",
    price: 829.99,
  },
  {
    _id: "32",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/3.JPG",
    price: 829.99,
  },
  {
    _id: "33",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/4.JPG",
    price: 829.99,
  },
  {
    _id: "34",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/5.JPG",
    price: 829.99,
  },
  {
    _id: "35",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/6.JPG",
    price: 829.99,
  },
  {
    _id: "36",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/7.JPG",
    price: 829.99,
  },
  {
    _id: "37",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/8.JPG",
    price: 829.99,
  },
  {
    _id: "38",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/9.JPG",
    price: 829.99,
  },
  {
    _id: "39",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/10.JPG",
    price: 829.99,
  },
  {
    _id: "40",
    name: "Texture",
    category: "bubble",
    image: "images/bubble/11.JPG",
    price: 829.99,
  },

  // glitz
  {
    _id: "41",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/01.JPG",
    price: 829.99,
  },
  {
    _id: "42",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/02.JPG",
    price: 829.99,
  },
  {
    _id: "43",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/03.JPG",
    price: 829.99,
  },
  {
    _id: "44",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/04.JPG",
    price: 829.99,
  },
  {
    _id: "45",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/05.JPG",
    price: 829.99,
  },
  {
    _id: "46",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/06.JPG",
    price: 829.99,
  },
  {
    _id: "47",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/07.JPG",
    price: 829.99,
  },
  {
    _id: "48",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/08.JPG",
    price: 829.99,
  },
  {
    _id: "49",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/09.JPG",
    price: 829.99,
  },
  {
    _id: "50",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/10.JPG",
    price: 829.99,
  },
  {
    _id: "51",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/11.JPG",
    price: 829.99,
  },
  {
    _id: "52",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/12.JPG",
    price: 829.99,
  },
  {
    _id: "53",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/13.JPG",
    price: 829.99,
  },
  {
    _id: "54",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/14.JPG",
    price: 829.99,
  },
  {
    _id: "55",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/15.JPG",
    price: 829.99,
  },
  {
    _id: "56",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/16.JPG",
    price: 829.99,
  },
  {
    _id: "57",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/17.JPG",
    price: 829.99,
  },
  {
    _id: "58",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/18.JPG",
    price: 829.99,
  },

  {
    _id: "59",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/19.JPG",
    price: 829.99,
  },
  {
    _id: "60",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/20.JPG",
    price: 829.99,
  },
  {
    _id: "61",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/21.JPG",
    price: 829.99,
  },
  {
    _id: "62",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/22.JPG",
    price: 829.99,
  },
  {
    _id: "63",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/23.JPG",
    price: 829.99,
  },
  {
    _id: "64",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/24.JPG",
    price: 829.99,
  },
  {
    _id: "65",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/25.JPG",
    price: 829.99,
  },
  {
    _id: "66",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/26.JPG",
    price: 829.99,
  },
  {
    _id: "67",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/27.JPG",
    price: 829.99,
  },
  {
    _id: "68",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/28.JPG",
    price: 829.99,
  },
  {
    _id: "69",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/29.JPG",
    price: 829.99,
  },
  {
    _id: "70",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/30.JPG",
    price: 829.99,
  },
  {
    _id: "71",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/31.JPG",
    price: 829.99,
  },
  {
    _id: "72",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/32.JPG",
    price: 829.99,
  },
  {
    _id: "73",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/33.JPG",
    price: 829.99,
  },
  {
    _id: "74",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/34.JPG",
    price: 829.99,
  },
  {
    _id: "75",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/35.JPG",
    price: 829.99,
  },
  {
    _id: "76",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/36.JPG",
    price: 829.99,
  },
  {
    _id: "77",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/37.JPG",
    price: 829.99,
  },
  {
    _id: "78",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/38.JPG",
    price: 829.99,
  },
  {
    _id: "79",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/39.JPG",
    price: 829.99,
  },
  {
    _id: "80",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/40.JPG",
    price: 829.99,
  },
  {
    _id: "81",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/41.JPG",
    price: 829.99,
  },
  {
    _id: "82",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/42.JPG",
    price: 829.99,
  },
  {
    _id: "83",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/43.JPG",
    price: 829.99,
  },
  {
    _id: "84",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/44.JPG",
    price: 829.99,
  },
  {
    _id: "85",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/45.JPG",
    price: 829.99,
  },
  {
    _id: "86",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/46.JPG",
    price: 829.99,
  },
  {
    _id: "87",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/47.JPG",
    price: 829.99,
  },
  {
    _id: "88",
    name: "Texture",
    category: "glitz",
    image: "images/glitz/48.JPG",
    price: 829.99,
  },

  // godess

  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/20.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/21.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/22.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/23.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/24.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/25.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "godess",
    image: "images/godess/26.JPG",
    price: 829.99,
  },

  // marbitto

  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/06.JPG",
    price: 829.99,
  },

  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "marbitto",
    image: "images/marbitto/18.JPG",
    price: 829.99,
  },

  // silicanogold
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-gold",
    image: "images/silicano-gold/20.JPG",
    price: 829.99,
  },

  // silicano-silver

  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/20.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/21.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/22.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/23.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/24.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/25.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/26.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/27.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/28.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/29.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/30.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/31.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/32.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/33.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/34.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/35.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "silicano-silver",
    image: "images/silicano-silver/36.JPG",
    price: 829.99,
  },

  // sparklz-metallic
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "sparklz-metallic",
    image: "images/sparklz-metallic/20.JPG",
    price: 829.99,
  },

  // swearl pearl

  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/20.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/21.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/22.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/23.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/24.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/25.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "swearl-pearl",
    image: "images/swearl-pearl/26.JPG",
    price: 829.99,
  },

  // Tango

  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "tango",
    image: "images/Tango/20.JPG",
    price: 829.99,
  },

  // velvetto

  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/01.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/02.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/03.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/04.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/05.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/06.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/07.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/08.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/09.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/10.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/11.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/12.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/13.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/14.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/15.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/16.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/17.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/18.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/19.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/20.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/21.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/22.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/23.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/24.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/25.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/26.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/27.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/28.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/29.JPG",
    price: 829.99,
  },
  {
    _id: "89",
    name: "Texture",
    category: "velvetto",
    image: "images/Velvetto/30.JPG",
    price: 829.99,
  },
];

export default products;
